# Generated by Django 4.2.4 on 2025-03-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('algemeen', 'Algemeen'), ('sport', 'Sport'), ('economie', 'Economie')], default='algemeen', max_length=20),
        ),
    ]
